name: Security Scan Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Export SonarCloud Report to JSON
        run: |
          mkdir -p /tmp/security-reports
          curl -X GET -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/issues/search?componentKeys=mekaizen_projectdevsecops2&types=BUG,VULNERABILITY,CODE_SMELL&ps=500" > /tmp/security-reports/sonar-report.json
          if ! jq empty /tmp/security-reports/sonar-report.json > /dev/null 2>&1; then
            echo "Error: Received invalid JSON from SonarCloud API"
            cat /tmp/security-reports/sonar-report.json
            exit 1
          fi

      - name: Convert JSON to HTML with Chart
        run: |
          {
            echo "<html><head><style>"
            echo "body { font-family: Arial, sans-serif; margin: 20px; background-color: #f4f4f4; }"
            echo "h2 { color: #4CAF50; }"
            echo "h3 { margin-top: 20px; }"
            echo "ul { list-style-type: none; padding: 0; }"
            echo "li { margin: 10px 0; padding: 8px; border: 1px solid #ddd; border-radius: 4px; background-color: white; }"
            echo ".severity-HIGH { color: #ff4d4d; font-weight: bold; }"
            echo ".severity-MEDIUM { color: #ffcc00; }"
            echo ".severity-LOW { color: #66bb6a; }"
            echo ".chart-container { width: 100%; max-width: 600px; margin: auto; }"
            echo "</style><script src='https://cdn.jsdelivr.net/npm/chart.js'></script></head><body>"
            echo "<h2>SonarCloud Issues Report</h2>"
            echo "<div class='chart-container'><canvas id='severityChart'></canvas></div>"
            echo "<h3>Issue Details</h3>"
            echo "<div id='issueDetails'></div>"
          } > /tmp/security-reports/sonar-report.html

          echo "<script>const issueData = {HIGH: 0, MEDIUM: 0, LOW: 0};" >> /tmp/security-reports/sonar-report.html
          echo "const issueDetails = [];</script>" >> /tmp/security-reports/sonar-report.html

          {
            # Collect issues according to severity and generate HTML
            echo "<h3>High Severity Issues</h3><ul>"
            jq -r '.issues[] | select(.severity == "BLOCKER" or .severity == "CRITICAL") | "<li class=\"severity-HIGH\">\(.message) - Severity: HIGH</li> ; issueData.HIGH++; issueDetails.push({ severity: 'HIGH', message: \(.message) })"' /tmp/security-reports/sonar-report.json
            echo "</ul><h3>Medium Severity Issues</h3><ul>"
            jq -r '.issues[] | select(.severity == "MAJOR") | "<li class=\"severity-MEDIUM\">\(.message) - Severity: MEDIUM</li> ; issueData.MEDIUM++; issueDetails.push({ severity: 'MEDIUM', message: \(.message) })"' /tmp/security-reports/sonar-report.json
            echo "</ul><h3>Low Severity Issues</h3><ul>"
            jq -r '.issues[] | select(.severity == "MINOR") | "<li class=\"severity-LOW\">\(.message) - Severity: LOW</li> ; issueData.LOW++; issueDetails.push({ severity: 'LOW', message: \(.message) })"' /tmp/security-reports/sonar-report.json
            echo "</ul>"
          } >> /tmp/security-reports/sonar-report.html

          echo "document.addEventListener('DOMContentLoaded', function(){"
          echo "const ctx = document.getElementById('severityChart').getContext('2d');"
          echo "new Chart(ctx, {"
          echo "type: 'bar',"
          echo "data: {"
          echo "labels: ['High', 'Medium', 'Low'],"
          echo "datasets: [{"
          echo "label: 'Number of Issues',"
          echo "data: [issueData.HIGH, issueData.MEDIUM, issueData.LOW],"
          echo "backgroundColor: ['#ff4d4d', '#ffcc00', '#66bb6a'],"
          echo "borderColor: 'rgba(255, 255, 255, 1)',"
          echo "borderWidth: 1"
          echo "}]"
          echo "},"
          echo "options: { scales: { y: { beginAtZero: true } } }"
          echo "});"
          echo "document.getElementById('issueDetails').innerHTML = issueDetails.map(i => '<div>' + i.message + ' (Severity: ' + i.severity + ')</div>').join('');"
          echo "});" >> /tmp/security-reports/sonar-report.html

          echo "</script></body></html>" >> /tmp/security-reports/sonar-report.html

      - name: Upload SonarCloud HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: sonar_report
          path: /tmp/security-reports/sonar-report.html
